package com.ramon.espn.dao;

import com.ramon.espn.model.Player;
import org.springframework.data.jpa.repository.JpaRepository;

/**
 * Player Repository Interface will be provided implementation by underlying
 * Spring boot jpa library. Basic CRUD features already implemented for all entity.
 * Any particular queries can be implemented using the entity attribute names.
 *
 */
public interface PlayerRepository extends JpaRepository<Player, Integer> {

    /**
     * sport is an attribute in the Player entity. So if you do findBy[AttributeName]
     * a query is generated by spring jpa that gets player by attribute name.
     *
     * i.e.
     * findBySport = Select * from Player where sport=[sport];
     *
     * @param sport
     * @return
     */
    Player findBySport(String sport);

}
